### ISSUE TITLE
Setting a body's moment to infinity

### ISSUE THREAD

**Issue by rolfson32** [kivy/kivent#113]
As a solution to prevent physics entities from rotating

**Comment by udiboy1209** [comment]
A more general solution discussed in #59.
A solution for now is to set the moment directly using `body.moment = float('inf')`.

After #121 is merged, you can pass moment as an arg, pass `float('inf')` along with `angular_velocity =0` to it to stop rotation.

**Comment by llfkj** [comment]
Should the moment also be set to float('inf') if `ang_vel_limit == 0`?

If it isn't, then objects will rotate (even though their ang_vel_limit was set to zero) if dragged (as, say, in example 5 via the mechanism of [examples/5_interacting_with_physics](https://github.com/kivy/kivent/tree/master/examples/5_interacting_with_physics).

<pre>
diff --git a/modules/cymunk/kivent_cymunk/physics.pyx b/modules/cymunk/kivent_cymunk/physics.pyx
index 0599d2f..e969bb9 100644
--- a/modules/cymunk/kivent_cymunk/physics.pyx
+++ b/modules/cymunk/kivent_cymunk/physics.pyx
@@ -407,6 +407,8 @@ cdef class CymunkPhysics(StaticMemGameSystem):
                 body.velocity_limit = args['vel_limit']
             if 'ang_vel_limit' in args:
                 body.angular_velocity_limit = args['ang_vel_limit']
+                if abs(args['ang_vel_limit']) < 0.00000001: # i.e. == 0?
+                    body.moment = float('inf')
         body.data = entity_id
         body.angle = args['angle']
         body.position = args['position']
</pre>

**Comment by udiboy1209** [comment]
@llfkj `ang_vel_limit` is passed on to Chipmunk-Physics which uses it to clamp angular velocity [here](https://github.com/tito/cymunk/blob/master/cymunk/Chipmunk-Physics/src/cpBody.c#L238). So I don't think setting moment to infinity in this special case should be necessary.

Have you tested whether `ang_vel_limit=0` works as expected? If it doesn't it looks like an upstream bug with [cymunk](https://github.com/tito/cymunk).

**Comment by Kovak** [comment]
You DO need to set moment to infinity if you absolutely do not want angular rotation. IIRC, the way chipmunk works, ang_vel_limit=0 prevents the object from having any angular momentum of its own, but does not stop it from possibly being affected by other forces. If you want a truly non-rotational body you want to set its moment to infinity as well. ang_vel_limit = 0 should not also set moment to infinity because they are 2 different settings with different use cases, for your particular use case you need to set both. But not for all use cases.

**Comment by udiboy1209** [comment]
@Kovak how else would a body have non-zero angular velocity if not for external forces or the initially set angular velocity. Does `ang_vel_limit` only limit the angular velocity set by the user and not by external forces? Seems counter-intuitive.

**Comment by llfkj** [comment]
@udiboy1209 Yes. To see, set the `ang_vel_limit` in the aforelinked example 5, and then drag a meteor to make a collision. It will begin to rotate (unless you somehow hit it dead-on)

Setting the moment for every object to `float('inf')` does indeed prevent rotations, but I guess I'm with @udiboy1209 in that I don't really understand what the `ang_vel_limit` is for now. Mind you, I haven't looked in the chipmunk2d code yet.

As a parallel, `velocity_limit` does indeed seem limit the body's velocity, even in the presence of external forces (such as those implemented in `interaction.pxd`), which is why I thought `ang_vel_limit` would behave as described above.

**Comment by udiboy1209** [comment]
@llfkj I tried the 5th example by setting `ang_vel_limit=0`. What I observed is that when I try to hit a meteor with another, it rotates a bit and the stops rotating and just moves. So essentially, except for the time just after collision the meteor does maintain zero angular velocity.

I haven't tested this but it looks like there is just one frame responsible for that single rotation after collision. `ang_vel_limit` applies after that and the meteor stops rotating. Again I haven't seen the chipmunk2d code to confirm this. I might be wrong too.

**Comment by llfkj** [comment]
@udiboy1209 Good point. The most noticeable rotation in my app was actually the object being dragged (which I failed to mention). If your sprites have a noticeable orientation (and unfortunately, the meteors don't), it's quite clear that they end up at all angles.

So the two cases where `ang_vel_limit` doesn't seem to apply is during a collision, and when you interact with the object via joint (a la `interaction.pyx`). Maybe this just needs to be noted in the `ang_vel_limit` documentation.

**Comment by Kovak** [comment]
Ok let me try to explain why this occurs. The simple answer is that this is how Chipmunk works, but the more complex answer is something like this:

ang_vel_limit is used like velocity limit to control the maximum angular velocity an object can have. So these properties affect the amount of internal velocity an object has.

Moment controls how much force it takes for an external object to transfer angular velocity to an object. 

Now, keep in mind that Chipmunk is an iterative solver. This means every single frame does not guarantee that the simulation is accurate because during certain frames and occurrences we may have some slight inaccuracies that the simulation will correct over a couple frames. For instance if 2 objects are slightly overlapping, they will not be pushed apart immediately so that they are no longer overlapping, they will be moved apart a little bit by little bit over several frames so that they do not develop jerky, unrealistic motions that would come from sudden velocity and position shifts of correcting immediately. 

Now, particularly with the touch system. The physics bodies that represent your fingers are essentially the Chipmunk2d equivalent of the philosophical 'unstoppable force', and so just as any time an unstoppable force hits a moveable object, the object moves. The appropriate way to fix this is to tell our object it is not amoveable object (ie, its movement is infinity). 

If you are more interested in this I highly suggest reading the Chipmunk2d docs themselves as well as the Chipmunk2d forums looking for posts relevant to whatever simulations you are doing.
