### ISSUE TITLE
iOS attention should be >= Android 

### ISSUE THREAD

**Issue by admincoder** [kivy/kivent#130]
Kivy-iOS is the only toolchain NOT supporting python 3, which is stopping Kivy from being a python 3 complete framework. I am new to Kivy, as well as Github but immediately fell in love with Kivy and the way it organizes it's sister projects with such modularity. 
From what I have seen Kivy has had slow release cycles, which is acceptable but only if the entire project benefits from a major release or rather have shorter release cycles that update bits of the framework at a time.

As a new mobile developer, I am ecstatic to use something like Kivy and take advantage of Python and it's ecosystem for cross platform development. But I noticed that in the mobile space, Android & Pyjnius are given way more attention than iOS & Pyobjus. This is very bad as the majority of the developer community worldwide prefers to release apps for iOS first before Android; better from a business point of view. Whether this is because of a lack of interest in iOS or a lack of devices to test, the issues must be made clearer and the core Kivy developers must ask for specific community help if needed.

Conclusion: @tito, @akshayaurora, @Kovak, @tshirtman, @dessant, @kived, @inclement, @Zen-CODE, and others.
Far more attention should be paid to iOS as a whole: Kivy-iOS [Python 3], Pyobjus, Plyer (iOS) and updated/more Kivy-iOS recipes. If for whatever reason (eg. No interest, No devices, etc.), Kivy core developers have trouble, they should explicitly list the kind of help wanted from the community.

I think it would be a good idea if people pledged their willingness to help.@Allactaga

+1 to help Kivy-iOS

**Comment by admincoder** [comment]
+1 to help Kivy-iOS.

**Comment by inclement** [comment]
Please stop opening the same issue in every repository. Given the problem you're raising, it's fine to just open it in the kivy (and possibly kivy-ios) repos.

**Comment by admincoder** [comment]
@inclement, sorry to cause problems but I needed to get some attention in the relevant projects.
@kovak, I only opened the issue in the needed repos, Kivy-iOS, Kivy and even Kivent because Kivent specifically talks about not being tested on iOS & OSX.

**Comment by dessant** [comment]
@admincoder, pinging everyone and telling them what they should focus on something is probably not the most costructive way to initiate change.
You'd be in a better position to point others' attention to an issue after you've also made your own contributions.

**Comment by admincoder** [comment]
@dessant, I will gladly take your advice. Could you tell me where to start on Python 3 support for iOS?

**Comment by dessant** [comment]
@admincoder, I haven't looked into what is exactly needed, but I would probably start by looking at the source, just like everyone else. :wink:

I would imagine you'd have to compile Python 3 for ios first, and for that you'd need a set of patches, just like for Python 2.
https://github.com/kivy/kivy-ios/tree/master/recipes/python

**Comment by Kovak** [comment]
In KivEnt's case this is largely a hardware access issue. I've personally owned only Android devices, and so mainly developed for them. It is only in the last 6 months thanks to a generous donation from a KivEnt supporter that I gained access to OSX hardware. 

I would love for KivEnt to have iOS as equal to Android. I started building KivEnt right out of college when I was unemployed and on food stamps; turns out at least some of us who spend a large amount of time building open-source software often don't have a large amount of funds, and we are actually building and using free things on account of that. The way I see it, if Apple users want equal support to everyone else they can donate to ensure their minority platform gets equal consideration.

Also, iOS is pretty much just the preferred platform for whale hunters, don't confuse that with the preferred platform for all application development. There are many use cases for Kivy where every platform but iOS is suitable, anything with a touch screen larger than an iPad to start.
