### ISSUE TITLE
buildozer android_new works with @master but not with @kivent-dev

### ISSUE THREAD

**Issue by mahomahomaho** [kivy/kivent#152]
Steps to reproduce: 
1. rm -rf ~/.buildozer .buildozer (just in case)
2. git clone -b recipe-kivent https://github.com/kived/python-for-android p4a
3. touch master.py
4. edit buildozer.spec to have body as below:

```
[app]
title = My Application
package.name = myapp
package.domain = org.test
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 0.1
requirements = kivy,kivent_core,kivent_cymunk,python2
orientation = landscape
fullscreen = 1
[buildozer]
log_level = 2
warn_on_root = 1
```
1. run command: 
   `VERSION_kivent_core=2.2-dev APP_ANDROID_P4A_DIR=$PWD/p4a/ buildozer --verbose android_new debug`

result: 

```
[INFO]:    kivent_cymunk first build failed (as expected)
[INFO]:    Running cython where appropriate
[INFO]:    Cythonize kivent_cymunk/physics.pyx
[DEBUG]:   -> running cython ./kivent_cymunk/physics.pyx
[INFO]:    Cythonize kivent_cymunk/interaction.pyx
[DEBUG]:   -> running cython ./kivent_cymunk/interaction.pyx
[DEBUG]:        warning: kivent_cymunk/interaction.pyx:549:20: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
[DEBUG]:        warning: kivent_cymunk/interaction.pyx:549:27: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
[DEBUG]:        warning: kivent_cymunk/interaction.pyx:728:20: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
[DEBUG]:        warning: kivent_cymunk/interaction.pyx:728:34: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
[DEBUG]:        warning: kivent_cymunk/interaction.pyx:758:20: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
[DEBUG]:        warning: kivent_cymunk/interaction.pyx:758:27: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
[DEBUG]:        warning: kivent_cymunk/interaction.pyx:758:43: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
[DEBUG]:   -> running python.host setup.py build_ext -v
[DEBUG]:        Traceback (most recent call last):
[DEBUG]:          File "setup.py", line 76, in <module>
[DEBUG]:            import cymunk
[DEBUG]:          File "/home/maho/workspace/khamster/try-2/.buildozer/android/platform/build/build/python-installs/myapp/lib/python2.7/site-packages/cymunk/__init__.py", line 1, in <module>
[DEBUG]:            from .cymunk import *
[DEBUG]:        ImportError: /home/maho/workspace/khamster/try-2/.buildozer/android/platform/build/build/python-installs/myapp/lib/python2.7/site-packages/cymunk/cymunk.so: wrong ELF class: ELFCLASS32
[INFO]:    STDOUT:
        Traceback (most recent call last):
  File "setup.py", line 76, in <module>
    import cymunk
  File "/home/maho/workspace/khamster/try-2/.buildozer/android/platform/build/build/python-installs/myapp/lib/python2.7/site-packages/cymunk/__init__.py", line 1, in <module>
    from .cymunk import *
ImportError: /home/maho/workspace/khamster/try-2/.buildozer/android/platform/build/build/python-installs/myapp/lib/python2.7/site-packages/cymunk/cymunk.so: wrong ELF class: ELFCLASS32
[INFO]:    STDERR:
```

but when I build with command:

`VERSION_kivent_core=master APP_ANDROID_P4A_DIR=$PWD/p4a/ buildozer --verbose android_new debug`

Then everything works as expected. 

full log of bad buils (with VERSION_kivent_core=2.2-dev)  and good build (with VERSION_kivent_core=master) is here: https://www.wetransfer.com/downloads/b748240c61e7810d56164284a43f418c20160713113034/5e30132ab0efe81bb6c70488cfa19dc720160713113034/3f4a89

related to #132 , https://github.com/kivy/python-for-android/pull/743 by @kived

**Comment by Kovak** [comment]
@mahomahomaho I wanted to address you directly on this since I missed you on irc today.

Android is a primary target for KivEnt, just as all other platforms are as well. However, I do not have infinite time in the world. One of the reason 2.2-dev is an in-development branch is that I have not had time to ensure that the Android build stays up to date, especially with python-for-androids major overhaul that has occurred in the last few months. I have still never used the new toolchain. One of the beauties of kivent is that typically I do not have to consider Android specifically when I'm working on extending features. I can happily spend months and years developing features and then other than working out pesky build related linking issues and such, I deploy the engine and it works. I always make sure to work out the linking issues for released code, and luckily thanks to @kived the python-for-android build issues arising from the new toolchain have been fixed for master.

Right now I am currently working on extending KivEnt's SVG features and mentoring our GSoC student @udiboy1209  who is working on Tiled integration. I just have not had time to dig into the new android build chain. I have a lot of volume of work unrelated to kivent or kivy, and moved cities just 2 weeks ago. 

This will get solved before the release of 2.2, but I have other features that are prioritized ahead of Android support to meet the needs of clients.

**Comment by mahomahomaho** [comment]
@Kovak - no offence please. I only was curious whad did you mean when
you said "I have not directly worked with android for years", if it's
still library for android or not.

**Comment by mahomahomaho** [comment]
okay, I finally know what is wrong and why it works on master and it doesn't in 2.2-dev

There is import cymunk in setup.py of kivent_cymunk, to get cymunk.get_include_dir()

Cymunk is built for ARM, while setup.py is running in x86 context, so there is elfclass mismatch. 

I don't know what should I do now, either remove import cymunk from setup.py, or modify recipe of cython to built both architectures of cython (I don't know how , yet).

**Comment by udiboy1209** [comment]
Does #155 completely fix this? Can this be closed @Kovak @mahomahomaho ?

**Comment by mahomahomaho** [comment]
I believe it can can be closed.
