### ISSUE TITLE
strange renderrer error

### ISSUE THREAD

**Issue by mahomahomaho** [kivy/kivent#159]
Hi, 

Look at modifed kivent example at https://github.com/mahomahomaho/kivy-testcase-renderer

When you run main.py, you should see appearing, seconds after seconds, three horizontal lines, where third is shorter than others. 

What you see instead, is that first two lines, became shorter when third line appears.

**Comment by Kovak** [comment]
This is because they end up modifying the same underlying model data. By default kivent reuse the same data for the same entity. If you want to modify individual entities models you need to create separate Models for them.

You should use Model_Manager.copy_model, or there are also do_copy kwargs for some of the other loading functions as well. For making entities this way you can also pass copy=True as one of the component initialization arguments.

**Comment by mahomahomaho** [comment]
On 02.09.2016 20:44, Kovak wrote:
> This is because they end up modifying the same underlying model data. By
> default kivent reuse the same data for the same entity. If you want to
> modify individual entities models you need to create separate Models for
> them.
> 
> You should use Model_Manager.copy_model, or there are also do_copy
> kwargs for some of the other loading functions as well. For making
> entities this way you can also pass copy=True as one of the component
> initialization arguments.

Oh, copy:True works, thanks.

But it's still unclear for me, why it happends like that. You said that
kivy reuse same data for the same entity. But it's different entity!

**Comment by Kovak** [comment]
reuse same underlying model data for every entity that use same texture by default. So even different entities will share data for their geometry.  So to have different data you must explicitly make a copy and edit it.
