### ISSUE TITLE
clear_entities possible bug

### ISSUE THREAD

**Issue by thegameguy** [kivy/kivent#254]
Hi, I have been having unexpected issues with gameworld.clear_entities(). please find the link below that produces the error.

main.py        https://pastebin.com/yjbYfSQL
traceback + Kv        https://pastebin.com/ZMjfB7Lz

Thanks!

**Comment by SleepProgger** [comment]
Thats a fun bug.

**Reason:**
This is happening because gameworlds `init_entity` doesn't copy the `component_order` argument, but stores the reference in the entity.
`remove_entity` (called by `clear_entities`) reverses this list inplace to remove the systems in the correct order.
Thus after a `remove_entity` call the supplied `components_order` argument is reversed and if used to create a new entity the initialization order is wrong.

**Workaround**
Just provide its own copy of the `component_order` to each init_entity call.

**Proposed Fix**
Simply copy the `component_order` in `init_entity`.
I'd propose to save the system_ids in the entities components_order instead of the names to safe a bit of  memory and lookups tho.

*PR with proposal for fix incoming *
