### ISSUE TITLE
another flickering

### ISSUE THREAD

**Issue by mahomahomaho** [kivy/kivent#79]
I'm not sure if it's related to #76 or not, and I wanted to avoid making too much mess there, so I open another issue. 

See  movie at url http://files.pagema.net/case2.ogv , flickering (or rather showing random previous drawings) starts from second=5. 

Logs from that run: http://files.pagema.net/kivy_15-07-30_54.txt (BTW - it's stupid that I cannot attach .txt file to github bugtracker)

Kivent used to run: https://github.com/mahomahomaho/KivEnt/tree/find_flickering - it's your last change + my Logger.debug in various places, 

Usecase is in:
```
   hg clone -r example2.1 http://bitbucket.org/maho/tmpkh2
```

Note, that it's different order of systems in .kv files, comparing to previous examples. 

As in #76 I had rough idea what is wrong, now I have none. I hope you will find out :)

**Comment by Kovak** [comment]
You should use the GameWorld.system_manager's update_order property to control the order your GameSystem's update in.

In example2.1 you are clock scheduling the entity removal. This means it is entirely possible to render a frame with the new and the old because the Clock schedule means "do NOT remove entity immediately, I don't care if there is a slight delay". You want to directly gameworld.remove_entity

I have pushed some fixes that clean up some internal rendering state, and there is a new Renderer property for your use case 'force_update'. Set force_update to True if you are doing a pattern like this one where you are creating and removing an entity every frame and triggering creation and deletion of batches over and over.

**Comment by mahomahomaho** [comment]
Oh man, it's finally solved (I hope that it's not just temporary random disappear of bug effects). I think that 4f277d749aa900e7723140067a499d2ef0efe274 is cure for my problems. 

BTW - I don't need to use force_update , it runs fine with force_update=False. 

Thank  you.
